print('-=' * 15)
print('VARIÁVEL UPPER - Atividade 02')
print('-=' * 15)

texto1 = str(input('Digite uma frase com letras minúsculas: '))
print()
print(texto1.upper(), '\nEu pedi minúsculas!!!')
texto2 = str(input('\nSó mais essa vez. Não esquece, minúsculas... '))
print()
print(texto2.upper(), '\nNão acredito!!! Já deu, tô fora!')
