print('-=' * 15)
print('COMENTÁRIOS - Atividade 05')
print('-=' * 15)

#print('\nAula de Introdução ao Python')
print('\nEsta é uma aula de programação')
#print('\nVimos que existem várias linguagens')
#print('\ncomo')
#print('\na linguagem Java!')
print('\nA linguagem que estamos utilizando é')
print('\na linguagem Python!')
print('\nNossa Aula é na')
#print('\nInfinity')
#print('\ntambém conhecida como')
print('\nInfinity School.')
print('\nBons códigos!')
#print('\nEsta Linha será um comentário em breve!')
